//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 
namespace GIBInterface.EFaturaPaketi.eSMM
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://earsiv.efatura.gov.tr", IsNullable = false)]
    public partial class eArsivVeri
    {

        private baslikType baslikField;

        private eArsivVeriSerbestMeslekMakbuz itemField;

        /// <remarks/>
        public baslikType baslik
        {
            get
            {
                return this.baslikField;
            }
            set
            {
                this.baslikField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serbestMeslekMakbuz")]
        public eArsivVeriSerbestMeslekMakbuz Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://earsiv.efatura.gov.tr")]
    public partial class baslikType
    {

        private vknTcknType mukellefField;

        private vknTcknType hazirlayanField;

        /// <remarks/>
        public vknTcknType mukellef
        {
            get
            {
                return this.mukellefField;
            }
            set
            {
                this.mukellefField = value;
            }
        }

        /// <remarks/>
        public vknTcknType hazirlayan
        {
            get
            {
                return this.hazirlayanField;
            }
            set
            {
                this.hazirlayanField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://earsiv.efatura.gov.tr")]
    public partial class vknTcknType
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tckn", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("vkn", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://earsiv.efatura.gov.tr", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        tckn,

        /// <remarks/>
        vkn,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://earsiv.efatura.gov.tr")]
    public partial class aliciType
    {

        private object itemField;

        private aliciTypeAdres adresField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gercekKisi", typeof(aliciTypeGercekKisi))]
        [System.Xml.Serialization.XmlElementAttribute("tuzelKisi", typeof(aliciTypeTuzelKisi))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public aliciTypeAdres adres
        {
            get
            {
                return this.adresField;
            }
            set
            {
                this.adresField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    public partial class aliciTypeGercekKisi
    {

        private string tcknField;

        private string adiSoyadiField;

        /// <remarks/>
        public string tckn
        {
            get
            {
                return this.tcknField;
            }
            set
            {
                this.tcknField = value;
            }
        }

        /// <remarks/>
        public string adiSoyadi
        {
            get
            {
                return this.adiSoyadiField;
            }
            set
            {
                this.adiSoyadiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    public partial class aliciTypeTuzelKisi
    {

        private string vknField;

        private string unvanField;

        /// <remarks/>
        public string vkn
        {
            get
            {
                return this.vknField;
            }
            set
            {
                this.vknField = value;
            }
        }

        /// <remarks/>
        public string unvan
        {
            get
            {
                return this.unvanField;
            }
            set
            {
                this.unvanField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    public partial class aliciTypeAdres
    {

        private string caddeSokakField;

        private string binaAdField;

        private string binaNoField;

        private string kapiNoField;

        private string kasabaKoyField;

        private string semtField;

        private string sehirField;

        private string postaKodField;

        private aliciTypeAdresUlke ulkeField;

        private string vDaireField;

        /// <remarks/>
        public string caddeSokak
        {
            get
            {
                return this.caddeSokakField;
            }
            set
            {
                this.caddeSokakField = value;
            }
        }

        /// <remarks/>
        public string binaAd
        {
            get
            {
                return this.binaAdField;
            }
            set
            {
                this.binaAdField = value;
            }
        }

        /// <remarks/>
        public string binaNo
        {
            get
            {
                return this.binaNoField;
            }
            set
            {
                this.binaNoField = value;
            }
        }

        /// <remarks/>
        public string kapiNo
        {
            get
            {
                return this.kapiNoField;
            }
            set
            {
                this.kapiNoField = value;
            }
        }

        /// <remarks/>
        public string kasabaKoy
        {
            get
            {
                return this.kasabaKoyField;
            }
            set
            {
                this.kasabaKoyField = value;
            }
        }

        /// <remarks/>
        public string semt
        {
            get
            {
                return this.semtField;
            }
            set
            {
                this.semtField = value;
            }
        }

        /// <remarks/>
        public string sehir
        {
            get
            {
                return this.sehirField;
            }
            set
            {
                this.sehirField = value;
            }
        }

        /// <remarks/>
        public string postaKod
        {
            get
            {
                return this.postaKodField;
            }
            set
            {
                this.postaKodField = value;
            }
        }

        /// <remarks/>
        public aliciTypeAdresUlke ulke
        {
            get
            {
                return this.ulkeField;
            }
            set
            {
                this.ulkeField = value;
            }
        }

        /// <remarks/>
        public string vDaire
        {
            get
            {
                return this.vDaireField;
            }
            set
            {
                this.vDaireField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    public enum aliciTypeAdresUlke
    {

        /// <remarks/>
        AF,

        /// <remarks/>
        AX,

        /// <remarks/>
        AL,

        /// <remarks/>
        DZ,

        /// <remarks/>
        AS,

        /// <remarks/>
        AD,

        /// <remarks/>
        AO,

        /// <remarks/>
        AI,

        /// <remarks/>
        AQ,

        /// <remarks/>
        AG,

        /// <remarks/>
        AR,

        /// <remarks/>
        AM,

        /// <remarks/>
        AW,

        /// <remarks/>
        AU,

        /// <remarks/>
        AT,

        /// <remarks/>
        AZ,

        /// <remarks/>
        BS,

        /// <remarks/>
        BH,

        /// <remarks/>
        BD,

        /// <remarks/>
        BB,

        /// <remarks/>
        BY,

        /// <remarks/>
        BE,

        /// <remarks/>
        BZ,

        /// <remarks/>
        BJ,

        /// <remarks/>
        BM,

        /// <remarks/>
        BT,

        /// <remarks/>
        BO,

        /// <remarks/>
        BA,

        /// <remarks/>
        BW,

        /// <remarks/>
        BV,

        /// <remarks/>
        BR,

        /// <remarks/>
        IO,

        /// <remarks/>
        BN,

        /// <remarks/>
        BG,

        /// <remarks/>
        BF,

        /// <remarks/>
        BI,

        /// <remarks/>
        KH,

        /// <remarks/>
        CM,

        /// <remarks/>
        CA,

        /// <remarks/>
        CV,

        /// <remarks/>
        KY,

        /// <remarks/>
        CF,

        /// <remarks/>
        TD,

        /// <remarks/>
        CL,

        /// <remarks/>
        CW,

        /// <remarks/>
        CN,

        /// <remarks/>
        CX,

        /// <remarks/>
        CC,

        /// <remarks/>
        CO,

        /// <remarks/>
        KM,

        /// <remarks/>
        CG,

        /// <remarks/>
        CD,

        /// <remarks/>
        CK,

        /// <remarks/>
        CR,

        /// <remarks/>
        CI,

        /// <remarks/>
        HR,

        /// <remarks/>
        CU,

        /// <remarks/>
        CY,

        /// <remarks/>
        CZ,

        /// <remarks/>
        DK,

        /// <remarks/>
        DJ,

        /// <remarks/>
        DM,

        /// <remarks/>
        DO,

        /// <remarks/>
        EC,

        /// <remarks/>
        EG,

        /// <remarks/>
        SV,

        /// <remarks/>
        GQ,

        /// <remarks/>
        ER,

        /// <remarks/>
        EE,

        /// <remarks/>
        ET,

        /// <remarks/>
        FK,

        /// <remarks/>
        FO,

        /// <remarks/>
        FJ,

        /// <remarks/>
        FI,

        /// <remarks/>
        FR,

        /// <remarks/>
        GF,

        /// <remarks/>
        PF,

        /// <remarks/>
        TF,

        /// <remarks/>
        GA,

        /// <remarks/>
        GM,

        /// <remarks/>
        GE,

        /// <remarks/>
        DE,

        /// <remarks/>
        GH,

        /// <remarks/>
        GI,

        /// <remarks/>
        GR,

        /// <remarks/>
        GL,

        /// <remarks/>
        GD,

        /// <remarks/>
        GP,

        /// <remarks/>
        GU,

        /// <remarks/>
        GT,

        /// <remarks/>
        GG,

        /// <remarks/>
        GN,

        /// <remarks/>
        GW,

        /// <remarks/>
        GY,

        /// <remarks/>
        HT,

        /// <remarks/>
        HM,

        /// <remarks/>
        VA,

        /// <remarks/>
        HN,

        /// <remarks/>
        HK,

        /// <remarks/>
        HU,

        /// <remarks/>
        IS,

        /// <remarks/>
        IN,

        /// <remarks/>
        ID,

        /// <remarks/>
        IR,

        /// <remarks/>
        IQ,

        /// <remarks/>
        IE,

        /// <remarks/>
        IM,

        /// <remarks/>
        IL,

        /// <remarks/>
        IT,

        /// <remarks/>
        JM,

        /// <remarks/>
        JP,

        /// <remarks/>
        JE,

        /// <remarks/>
        JO,

        /// <remarks/>
        KZ,

        /// <remarks/>
        KE,

        /// <remarks/>
        KI,

        /// <remarks/>
        KP,

        /// <remarks/>
        KR,

        /// <remarks/>
        KW,

        /// <remarks/>
        KG,

        /// <remarks/>
        LA,

        /// <remarks/>
        LV,

        /// <remarks/>
        LB,

        /// <remarks/>
        LS,

        /// <remarks/>
        LR,

        /// <remarks/>
        LY,

        /// <remarks/>
        LI,

        /// <remarks/>
        LT,

        /// <remarks/>
        LU,

        /// <remarks/>
        MO,

        /// <remarks/>
        MK,

        /// <remarks/>
        MG,

        /// <remarks/>
        MW,

        /// <remarks/>
        MY,

        /// <remarks/>
        MV,

        /// <remarks/>
        ML,

        /// <remarks/>
        MT,

        /// <remarks/>
        MH,

        /// <remarks/>
        MQ,

        /// <remarks/>
        MR,

        /// <remarks/>
        MU,

        /// <remarks/>
        YT,

        /// <remarks/>
        MX,

        /// <remarks/>
        FM,

        /// <remarks/>
        MD,

        /// <remarks/>
        MC,

        /// <remarks/>
        MN,

        /// <remarks/>
        ME,

        /// <remarks/>
        MS,

        /// <remarks/>
        MA,

        /// <remarks/>
        MZ,

        /// <remarks/>
        MM,

        /// <remarks/>
        NA,

        /// <remarks/>
        NR,

        /// <remarks/>
        NP,

        /// <remarks/>
        NL,

        /// <remarks/>
        AN,

        /// <remarks/>
        NC,

        /// <remarks/>
        NZ,

        /// <remarks/>
        NI,

        /// <remarks/>
        NE,

        /// <remarks/>
        NG,

        /// <remarks/>
        NU,

        /// <remarks/>
        NF,

        /// <remarks/>
        MP,

        /// <remarks/>
        NO,

        /// <remarks/>
        OM,

        /// <remarks/>
        PK,

        /// <remarks/>
        PW,

        /// <remarks/>
        PS,

        /// <remarks/>
        PA,

        /// <remarks/>
        PG,

        /// <remarks/>
        PY,

        /// <remarks/>
        PE,

        /// <remarks/>
        PH,

        /// <remarks/>
        PN,

        /// <remarks/>
        PL,

        /// <remarks/>
        PT,

        /// <remarks/>
        PR,

        /// <remarks/>
        QA,

        /// <remarks/>
        RE,

        /// <remarks/>
        RO,

        /// <remarks/>
        RU,

        /// <remarks/>
        RW,

        /// <remarks/>
        BL,

        /// <remarks/>
        SH,

        /// <remarks/>
        KN,

        /// <remarks/>
        LC,

        /// <remarks/>
        MF,

        /// <remarks/>
        PM,

        /// <remarks/>
        VC,

        /// <remarks/>
        WS,

        /// <remarks/>
        SM,

        /// <remarks/>
        ST,

        /// <remarks/>
        SA,

        /// <remarks/>
        SN,

        /// <remarks/>
        RS,

        /// <remarks/>
        SC,

        /// <remarks/>
        SL,

        /// <remarks/>
        SG,

        /// <remarks/>
        SK,

        /// <remarks/>
        SI,

        /// <remarks/>
        SB,

        /// <remarks/>
        SO,

        /// <remarks/>
        ZA,

        /// <remarks/>
        GS,

        /// <remarks/>
        ES,

        /// <remarks/>
        LK,

        /// <remarks/>
        SD,

        /// <remarks/>
        SR,

        /// <remarks/>
        SJ,

        /// <remarks/>
        SZ,

        /// <remarks/>
        SE,

        /// <remarks/>
        CH,

        /// <remarks/>
        SY,

        /// <remarks/>
        TW,

        /// <remarks/>
        TJ,

        /// <remarks/>
        TZ,

        /// <remarks/>
        TH,

        /// <remarks/>
        TL,

        /// <remarks/>
        TG,

        /// <remarks/>
        TK,

        /// <remarks/>
        TO,

        /// <remarks/>
        TT,

        /// <remarks/>
        TN,

        /// <remarks/>
        TR,

        /// <remarks/>
        TM,

        /// <remarks/>
        TC,

        /// <remarks/>
        TV,

        /// <remarks/>
        UG,

        /// <remarks/>
        UA,

        /// <remarks/>
        AE,

        /// <remarks/>
        GB,

        /// <remarks/>
        US,

        /// <remarks/>
        UM,

        /// <remarks/>
        UY,

        /// <remarks/>
        UZ,

        /// <remarks/>
        VU,

        /// <remarks/>
        VE,

        /// <remarks/>
        VN,

        /// <remarks/>
        VG,

        /// <remarks/>
        VI,

        /// <remarks/>
        WF,

        /// <remarks/>
        EH,

        /// <remarks/>
        YE,

        /// <remarks/>
        ZM,

        /// <remarks/>
        ZW,

        /// <remarks/>
        CTR,

        /// <remarks/>
        XK,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://earsiv.efatura.gov.tr")]
    public partial class vergiBilgiType
    {

        private decimal vergilerToplamiField;

        private vergiBilgiTypeVergi[] vergiField;

        private vergiBilgiTypeTevkifat[] tevkifatField;

        /// <remarks/>
        public decimal vergilerToplami
        {
            get
            {
                return this.vergilerToplamiField;
            }
            set
            {
                this.vergilerToplamiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vergi")]
        public vergiBilgiTypeVergi[] vergi
        {
            get
            {
                return this.vergiField;
            }
            set
            {
                this.vergiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tevkifat")]
        public vergiBilgiTypeTevkifat[] tevkifat
        {
            get
            {
                return this.tevkifatField;
            }
            set
            {
                this.tevkifatField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    public partial class vergiBilgiTypeVergi
    {

        private decimal matrahField;

        private vergiBilgiTypeVergiVergiKodu vergiKoduField;

        private decimal vergiTutariField;

        private decimal vergiOraniField;

        private bool vergiOraniFieldSpecified;

        /// <remarks/>
        public decimal matrah
        {
            get
            {
                return this.matrahField;
            }
            set
            {
                this.matrahField = value;
            }
        }

        /// <remarks/>
        public vergiBilgiTypeVergiVergiKodu vergiKodu
        {
            get
            {
                return this.vergiKoduField;
            }
            set
            {
                this.vergiKoduField = value;
            }
        }

        /// <remarks/>
        public decimal vergiTutari
        {
            get
            {
                return this.vergiTutariField;
            }
            set
            {
                this.vergiTutariField = value;
            }
        }

        /// <remarks/>
        public decimal vergiOrani
        {
            get
            {
                return this.vergiOraniField;
            }
            set
            {
                this.vergiOraniField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vergiOraniSpecified
        {
            get
            {
                return this.vergiOraniFieldSpecified;
            }
            set
            {
                this.vergiOraniFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    public enum vergiBilgiTypeVergiVergiKodu
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0003")]
        Item0003,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0011")]
        Item0011,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0015")]
        Item0015,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0021")]
        Item0021,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0061")]
        Item0061,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0071")]
        Item0071,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0073")]
        Item0073,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0074")]
        Item0074,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0075")]
        Item0075,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0076")]
        Item0076,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0077")]
        Item0077,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1047")]
        Item1047,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1048")]
        Item1048,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4080")]
        Item4080,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4081")]
        Item4081,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4171")]
        Item4171,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9015")]
        Item9015,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9021")]
        Item9021,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9077")]
        Item9077,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8001")]
        Item8001,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8002")]
        Item8002,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4071")]
        Item4071,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8004")]
        Item8004,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8005")]
        Item8005,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8006")]
        Item8006,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8007")]
        Item8007,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8008")]
        Item8008,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9040")]
        Item9040,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    public partial class vergiBilgiTypeTevkifat
    {

        private string tevkifatKoduField;

        private decimal tevkifatTutariField;

        private decimal tevkifatOraniField;

        /// <remarks/>
        public string tevkifatKodu
        {
            get
            {
                return this.tevkifatKoduField;
            }
            set
            {
                this.tevkifatKoduField = value;
            }
        }

        /// <remarks/>
        public decimal tevkifatTutari
        {
            get
            {
                return this.tevkifatTutariField;
            }
            set
            {
                this.tevkifatTutariField = value;
            }
        }

        /// <remarks/>
        public decimal tevkifatOrani
        {
            get
            {
                return this.tevkifatOraniField;
            }
            set
            {
                this.tevkifatOraniField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    public partial class eArsivVeriSerbestMeslekMakbuz
    {

        private string makbuzNoField;

        private string eTTNField;

        private eArsivVeriSerbestMeslekMakbuzGonderimSekli gonderimSekliField;

        private string dosyaAdiField;

        private System.DateTime belgeTarihiField;

        private System.DateTime belgeZamaniField;

        private bool belgeZamaniFieldSpecified;

        private decimal toplamTutarField;

        private decimal odenecekTutarField;

        private eArsivVeriSerbestMeslekMakbuzParaBirimi paraBirimiField;

        private decimal kurField;

        private bool kurFieldSpecified;

        private vergiBilgiType vergiBilgisiField;

        private aliciType aliciBilgileriField;

        private eArsivVeriSerbestMeslekMakbuzYnOkcFisBilgisi[] ynOkcFisBilgisiField;

        private eArsivVeriSerbestMeslekMakbuzMalHizmet[] malHizmetBilgisiField;

        /// <remarks/>
        public string makbuzNo
        {
            get
            {
                return this.makbuzNoField;
            }
            set
            {
                this.makbuzNoField = value;
            }
        }

        /// <remarks/>
        public string ETTN
        {
            get
            {
                return this.eTTNField;
            }
            set
            {
                this.eTTNField = value;
            }
        }

        /// <remarks/>
        public eArsivVeriSerbestMeslekMakbuzGonderimSekli gonderimSekli
        {
            get
            {
                return this.gonderimSekliField;
            }
            set
            {
                this.gonderimSekliField = value;
            }
        }

        /// <remarks/>
        public string dosyaAdi
        {
            get
            {
                return this.dosyaAdiField;
            }
            set
            {
                this.dosyaAdiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime belgeTarihi
        {
            get
            {
                return this.belgeTarihiField;
            }
            set
            {
                this.belgeTarihiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime belgeZamani
        {
            get
            {
                return this.belgeZamaniField;
            }
            set
            {
                this.belgeZamaniField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool belgeZamaniSpecified
        {
            get
            {
                return this.belgeZamaniFieldSpecified;
            }
            set
            {
                this.belgeZamaniFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal toplamTutar
        {
            get
            {
                return this.toplamTutarField;
            }
            set
            {
                this.toplamTutarField = value;
            }
        }

        /// <remarks/>
        public decimal odenecekTutar
        {
            get
            {
                return this.odenecekTutarField;
            }
            set
            {
                this.odenecekTutarField = value;
            }
        }

        /// <remarks/>
        public eArsivVeriSerbestMeslekMakbuzParaBirimi paraBirimi
        {
            get
            {
                return this.paraBirimiField;
            }
            set
            {
                this.paraBirimiField = value;
            }
        }

        /// <remarks/>
        public decimal kur
        {
            get
            {
                return this.kurField;
            }
            set
            {
                this.kurField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool kurSpecified
        {
            get
            {
                return this.kurFieldSpecified;
            }
            set
            {
                this.kurFieldSpecified = value;
            }
        }

        /// <remarks/>
        public vergiBilgiType vergiBilgisi
        {
            get
            {
                return this.vergiBilgisiField;
            }
            set
            {
                this.vergiBilgisiField = value;
            }
        }

        /// <remarks/>
        public aliciType aliciBilgileri
        {
            get
            {
                return this.aliciBilgileriField;
            }
            set
            {
                this.aliciBilgileriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ynOkcFisBilgisi")]
        public eArsivVeriSerbestMeslekMakbuzYnOkcFisBilgisi[] ynOkcFisBilgisi
        {
            get
            {
                return this.ynOkcFisBilgisiField;
            }
            set
            {
                this.ynOkcFisBilgisiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("malHizmet", IsNullable = false)]
        public eArsivVeriSerbestMeslekMakbuzMalHizmet[] malHizmetBilgisi
        {
            get
            {
                return this.malHizmetBilgisiField;
            }
            set
            {
                this.malHizmetBilgisiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    public enum eArsivVeriSerbestMeslekMakbuzGonderimSekli
    {

        /// <remarks/>
        KAGIT,

        /// <remarks/>
        ELEKTRONIK,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    public enum eArsivVeriSerbestMeslekMakbuzParaBirimi
    {

        /// <remarks/>
        AED,

        /// <remarks/>
        AFN,

        /// <remarks/>
        ALL,

        /// <remarks/>
        AMD,

        /// <remarks/>
        ANG,

        /// <remarks/>
        AOA,

        /// <remarks/>
        ARS,

        /// <remarks/>
        AUD,

        /// <remarks/>
        AWG,

        /// <remarks/>
        AZN,

        /// <remarks/>
        BAM,

        /// <remarks/>
        BBD,

        /// <remarks/>
        BDT,

        /// <remarks/>
        BGN,

        /// <remarks/>
        BHD,

        /// <remarks/>
        BIF,

        /// <remarks/>
        BMD,

        /// <remarks/>
        BND,

        /// <remarks/>
        BOB,

        /// <remarks/>
        BOV,

        /// <remarks/>
        BRL,

        /// <remarks/>
        BSD,

        /// <remarks/>
        BTN,

        /// <remarks/>
        BWP,

        /// <remarks/>
        BYN,

        /// <remarks/>
        BZD,

        /// <remarks/>
        CAD,

        /// <remarks/>
        CDF,

        /// <remarks/>
        CHE,

        /// <remarks/>
        CHF,

        /// <remarks/>
        CHW,

        /// <remarks/>
        CLF,

        /// <remarks/>
        CLP,

        /// <remarks/>
        CNY,

        /// <remarks/>
        COP,

        /// <remarks/>
        COU,

        /// <remarks/>
        CRC,

        /// <remarks/>
        CUC,

        /// <remarks/>
        CUP,

        /// <remarks/>
        CVE,

        /// <remarks/>
        CZK,

        /// <remarks/>
        DJF,

        /// <remarks/>
        DKK,

        /// <remarks/>
        DOP,

        /// <remarks/>
        DZD,

        /// <remarks/>
        EGP,

        /// <remarks/>
        ERN,

        /// <remarks/>
        ETB,

        /// <remarks/>
        EUR,

        /// <remarks/>
        FJD,

        /// <remarks/>
        FKP,

        /// <remarks/>
        GBP,

        /// <remarks/>
        GEL,

        /// <remarks/>
        GHS,

        /// <remarks/>
        GIP,

        /// <remarks/>
        GMD,

        /// <remarks/>
        GNF,

        /// <remarks/>
        GTQ,

        /// <remarks/>
        GYD,

        /// <remarks/>
        HKD,

        /// <remarks/>
        HNL,

        /// <remarks/>
        HRK,

        /// <remarks/>
        HTG,

        /// <remarks/>
        HUF,

        /// <remarks/>
        IDR,

        /// <remarks/>
        ILS,

        /// <remarks/>
        INR,

        /// <remarks/>
        IQD,

        /// <remarks/>
        IRR,

        /// <remarks/>
        ISK,

        /// <remarks/>
        JMD,

        /// <remarks/>
        JOD,

        /// <remarks/>
        JPY,

        /// <remarks/>
        KES,

        /// <remarks/>
        KGS,

        /// <remarks/>
        KHR,

        /// <remarks/>
        KMF,

        /// <remarks/>
        KPW,

        /// <remarks/>
        KRW,

        /// <remarks/>
        KWD,

        /// <remarks/>
        KYD,

        /// <remarks/>
        KZT,

        /// <remarks/>
        LAK,

        /// <remarks/>
        LBP,

        /// <remarks/>
        LKR,

        /// <remarks/>
        LRD,

        /// <remarks/>
        LSL,

        /// <remarks/>
        LTL,

        /// <remarks/>
        LVL,

        /// <remarks/>
        LYD,

        /// <remarks/>
        MAD,

        /// <remarks/>
        MDL,

        /// <remarks/>
        MGA,

        /// <remarks/>
        MKD,

        /// <remarks/>
        MMK,

        /// <remarks/>
        MNT,

        /// <remarks/>
        MOP,

        /// <remarks/>
        MRU,

        /// <remarks/>
        MUR,

        /// <remarks/>
        MVR,

        /// <remarks/>
        MWK,

        /// <remarks/>
        MXN,

        /// <remarks/>
        MXV,

        /// <remarks/>
        MYR,

        /// <remarks/>
        MZN,

        /// <remarks/>
        NAD,

        /// <remarks/>
        NGN,

        /// <remarks/>
        NIO,

        /// <remarks/>
        NOK,

        /// <remarks/>
        NPR,

        /// <remarks/>
        NZD,

        /// <remarks/>
        OMR,

        /// <remarks/>
        PAB,

        /// <remarks/>
        PEN,

        /// <remarks/>
        PGK,

        /// <remarks/>
        PHP,

        /// <remarks/>
        PKR,

        /// <remarks/>
        PLN,

        /// <remarks/>
        PYG,

        /// <remarks/>
        QAR,

        /// <remarks/>
        RON,

        /// <remarks/>
        RSD,

        /// <remarks/>
        RUB,

        /// <remarks/>
        RWF,

        /// <remarks/>
        SAR,

        /// <remarks/>
        SBD,

        /// <remarks/>
        SCR,

        /// <remarks/>
        SDG,

        /// <remarks/>
        SEK,

        /// <remarks/>
        SGD,

        /// <remarks/>
        SHP,

        /// <remarks/>
        SLL,

        /// <remarks/>
        SOS,

        /// <remarks/>
        SRD,

        /// <remarks/>
        SSP,

        /// <remarks/>
        STD,

        /// <remarks/>
        SVC,

        /// <remarks/>
        SYP,

        /// <remarks/>
        SZL,

        /// <remarks/>
        THB,

        /// <remarks/>
        TJS,

        /// <remarks/>
        TMT,

        /// <remarks/>
        TND,

        /// <remarks/>
        TOP,

        /// <remarks/>
        TRY,

        /// <remarks/>
        TTD,

        /// <remarks/>
        TWD,

        /// <remarks/>
        TZS,

        /// <remarks/>
        UAH,

        /// <remarks/>
        UGX,

        /// <remarks/>
        USD,

        /// <remarks/>
        USN,

        /// <remarks/>
        USS,

        /// <remarks/>
        UYI,

        /// <remarks/>
        UYU,

        /// <remarks/>
        UZS,

        /// <remarks/>
        VEF,

        /// <remarks/>
        VND,

        /// <remarks/>
        VUV,

        /// <remarks/>
        WST,

        /// <remarks/>
        XAF,

        /// <remarks/>
        XAG,

        /// <remarks/>
        XAU,

        /// <remarks/>
        XBA,

        /// <remarks/>
        XBB,

        /// <remarks/>
        XBC,

        /// <remarks/>
        XBD,

        /// <remarks/>
        XCD,

        /// <remarks/>
        XDR,

        /// <remarks/>
        XFU,

        /// <remarks/>
        XOF,

        /// <remarks/>
        XPD,

        /// <remarks/>
        XPF,

        /// <remarks/>
        XPT,

        /// <remarks/>
        XSU,

        /// <remarks/>
        XTS,

        /// <remarks/>
        XUA,

        /// <remarks/>
        XXX,

        /// <remarks/>
        YER,

        /// <remarks/>
        ZAR,

        /// <remarks/>
        ZMK,

        /// <remarks/>
        ZWL,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    public partial class eArsivVeriSerbestMeslekMakbuzYnOkcFisBilgisi
    {

        private string okcSeriNoField;

        private string zNoField;

        private string fisNoField;

        private eArsivVeriSerbestMeslekMakbuzYnOkcFisBilgisiFisTip fisTipField;

        private System.DateTime fisTarihField;

        private System.DateTime fisZamanField;

        private bool fisZamanFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string okcSeriNo
        {
            get
            {
                return this.okcSeriNoField;
            }
            set
            {
                this.okcSeriNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zNo
        {
            get
            {
                return this.zNoField;
            }
            set
            {
                this.zNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fisNo
        {
            get
            {
                return this.fisNoField;
            }
            set
            {
                this.fisNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public eArsivVeriSerbestMeslekMakbuzYnOkcFisBilgisiFisTip fisTip
        {
            get
            {
                return this.fisTipField;
            }
            set
            {
                this.fisTipField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime fisTarih
        {
            get
            {
                return this.fisTarihField;
            }
            set
            {
                this.fisTarihField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "time")]
        public System.DateTime fisZaman
        {
            get
            {
                return this.fisZamanField;
            }
            set
            {
                this.fisZamanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fisZamanSpecified
        {
            get
            {
                return this.fisZamanFieldSpecified;
            }
            set
            {
                this.fisZamanFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    public enum eArsivVeriSerbestMeslekMakbuzYnOkcFisBilgisiFisTip
    {

        /// <remarks/>
        AVANS,

        /// <remarks/>
        YEMEK_FIS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("E-FATURA")]
        EFATURA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("E-FATURA_IRSALIYE")]
        EFATURA_IRSALIYE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("E-ARSIV")]
        EARSIV,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("E-ARSIV_IRSALIYE")]
        EARSIV_IRSALIYE,

        /// <remarks/>
        FATURA,

        /// <remarks/>
        OTOPARK,

        /// <remarks/>
        FATURA_TAHSILAT,

        /// <remarks/>
        FATURA_TAHSILAT_KOMISYONLU,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://earsiv.efatura.gov.tr")]
    public partial class eArsivVeriSerbestMeslekMakbuzMalHizmet
    {

        private string adField;

        private vergiBilgiType vergiBilgisiField;

        private decimal burutUcretField;

        /// <remarks/>
        public string ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }

        /// <remarks/>
        public vergiBilgiType vergiBilgisi
        {
            get
            {
                return this.vergiBilgisiField;
            }
            set
            {
                this.vergiBilgisiField = value;
            }
        }

        /// <remarks/>
        public decimal burutUcret
        {
            get
            {
                return this.burutUcretField;
            }
            set
            {
                this.burutUcretField = value;
            }
        }
    }
}
